;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        isearch-delete-char
        isearch-exit
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        smex
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        isearch-other-control-char
        keyboard-escape-quit
        sgml-slash
        ))
